<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <groupId>org.example</groupId>
    <artifactId>game</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <name>game/dev</name>
  <artifactId>game-dev</artifactId>
  <modelVersion>4.0.0</modelVersion>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <properties>
    <game.generated.directory>${project.build.directory}/generated-sources/game
    </game.generated.directory>
  </properties>

  <profiles>
    <profile>
      <id>game</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <properties>
        <main.class>org.example.game.GameStart</main.class>
        <filename>game</filename>
        <outputdir>${project.build.directory}/release/game</outputdir>
      </properties>
    </profile>
    <profile>
      <id>world</id>
      <properties>
        <main.class>org.example.world.WorldStart</main.class>
        <filename>world</filename>
        <outputdir>${project.build.directory}/release/world</outputdir>
      </properties>
    </profile>
  </profiles>

  <build>
    <finalName>${filename}</finalName>
    <plugins>

      <!-- package -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.2.0</version>
        <configuration>
          <excludes>
            <!-- don't copy resources to jar -->
            <exclude>*.properties</exclude>
            <exclude>*.xml</exclude>
          </excludes>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
            </manifest>
            <manifestEntries>
              <Class-Path>./</Class-Path>
            </manifestEntries>
          </archive>
          <outputDirectory>${outputdir}</outputDirectory>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <mainClass>${main.class}</mainClass>
          <outputDirectory>${outputdir}</outputDirectory>
          <layout>JAR</layout>
        </configuration>
      </plugin>

      <!--resource copy -->
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-resources</id>
            <!-- here the phase you need -->
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${outputdir}</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/resources</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!--      &lt;!&ndash; 添加 exec-maven-plugin 插件 &ndash;&gt;-->
      <!--      <plugin>-->
      <!--        <groupId>org.codehaus.mojo</groupId>-->
      <!--        <artifactId>exec-maven-plugin</artifactId>-->
      <!--        <executions>-->
      <!--          <execution>-->
      <!--            <id>codeGenerator</id>-->
      <!--            &lt;!&ndash; 选择一个合适的 Maven 构建生命周期阶段 &ndash;&gt;-->
      <!--            <phase>compile</phase>-->
      <!--            <goals>-->
      <!--              <goal>java</goal>-->
      <!--            </goals>-->
      <!--            <configuration>-->
      <!--              <mainClass>org.example.common.SourceCodeGenerator</mainClass>-->
      <!--              &lt;!&ndash; 传递给 Java 应用程序的命令行参数 &ndash;&gt;-->
      <!--              <arguments>-->
      <!--                <argument>${game.generated.directory}</argument>-->
      <!--              </arguments>-->
      <!--            </configuration>-->
      <!--          </execution>-->
      <!--        </executions>-->
      <!--      </plugin>-->

      <!--      &lt;!&ndash; 生成的业务代码其所在的目录，需要加入到编译路径中 &ndash;&gt;-->
      <!--      <plugin>-->
      <!--        <groupId>org.codehaus.mojo</groupId>-->
      <!--        <artifactId>build-helper-maven-plugin</artifactId>-->
      <!--        <version>3.0.0</version>-->
      <!--        <executions>-->
      <!--          <execution>-->
      <!--            <phase>compile</phase>-->
      <!--            <goals>-->
      <!--              <goal>add-source</goal>-->
      <!--            </goals>-->
      <!--            <configuration>-->
      <!--              <sources>-->
      <!--                <source>${game.generated.directory}-->
      <!--                </source>&lt;!&ndash; adjust folder name to your needs &ndash;&gt;-->
      <!--              </sources>-->
      <!--            </configuration>-->
      <!--          </execution>-->
      <!--        </executions>-->
      <!--      </plugin>-->

      <!--      <plugin>-->
      <!--        <groupId>org.apache.maven.plugins</groupId>-->
      <!--        <artifactId>maven-compiler-plugin</artifactId>-->
      <!--        <configuration>-->
      <!--          <source>${maven.compiler.source}</source>-->
      <!--          <target>${maven.compiler.target}</target>-->
      <!--          <encoding>${project.build.sourceEncoding}</encoding>-->
      <!--        </configuration>-->

      <!--        <executions>-->
      <!--          <execution>-->
      <!--            <id>game-generated-compile</id>-->
      <!--            <phase>compile</phase>-->
      <!--            <goals>-->
      <!--              <goal>compile</goal>-->
      <!--            </goals>-->
      <!--          </execution>-->
      <!--        </executions>-->
      <!--      </plugin>-->


    </plugins>
  </build>

  <dependencies>
    <!-- https://mvnrepository.com/artifact/io.github.classgraph/classgraph -->
    <!--    <dependency>-->
    <!--      <groupId>io.github.classgraph</groupId>-->
    <!--      <artifactId>classgraph</artifactId>-->
    <!--    </dependency>-->

    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>game-util</artifactId>
      <version>${project.version}</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.auto.service</groupId>
          <artifactId>auto-service</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- spring -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
    </dependency>

    <!-- https://mvnrepository.com/artifact/javax.annotation/javax.annotation-api -->
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
    </dependency>

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-buffer</artifactId>
    </dependency>

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport</artifactId>
    </dependency>

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
    </dependency>

    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
    </dependency>

    <!-- logging -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j-impl</artifactId>
    </dependency>

    <!-- mongodb -->
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-sync</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
    </dependency>

  </dependencies>


</project>